
LLVM_BUILD=${LLVM_HOME}/build

LLVM_INC=-I. -I${LLVM_HOME}/include

MACROS=-D __STDC_LIMIT_MACROS \
       -D__STDC_CONSTANT_MACROS

all: compile

compile: 
	make -C ${LLVM_BUILD} ${LLVM_INC} > /dev/null

clean:
	make -C ${LLVM_BUILD} clean

